package me.MiniDigger.Core.Stats;

public enum ActionType {
	TPS,
	KILL, // TOIMPLEMENT
	DEATH, // TOIMPLEMENT
	JOIN,
	SWITCH, // TOIMPLEMENT
	LEAVE,
	WIN, // TOIMPLEMENT
	LOSS, // TOIMPLEMENT
	KICK, // TOIMPLEMENT
	BAN, // TOIMPLEMENT
	PARDON, // TOIMPLEMENT
	ITEM_PICKUP,
	ITEM_DROP,
	ITEM_CRAFT, // TOIMPLEMENT
	ITEM_BREAK,
	ITEM_EATEN,
	CHEST_OPENED, // TOIMPLEMENT
	LINE_CHATTED, // TOIMPLEMENT
	COMMAND_EXECUTED, // TOIMPLEMENT
	ARROW_SHOT, // TOIMPLEMENT
	XP_COLLECTED, // TOIMPLEMENT
	DAMAGE_TAKEN, // TOIMPLEMENT
	ON_FIRE, // TOIMPLEMENT
	VOTE, // TOIMPLEMENT
	BUCKET_FILLED, // TOIMPLEMENT
	BUCKET_EMPTIED, // TOIMPLEMENT
	VILLAGER_TRADE, // TOIMPLEMENT
	TOKEN_EARNED, // TOIMPLEMENT
	CRANK_EXPLOEDED, // TOIMPLEMENT
	SERVER_RESTART,
}
