package me.MiniDigger.Core.Stats;

public enum ActionType {
	TPS,
	KILL, // TOIMPLEMENT
	DEATH, // TOIMPLEMENT
	JOIN, // TOIMPLEMENT
	SWITCH, // TOIMPLEMENT
	LEAVE, // TOIMPLEMENT
	WIN, // TOIMPLEMENT
	LOSS, // TOIMPLEMENT
	KICK, // TOIMPLEMENT
	BAN, // TOIMPLEMENT
	PARDON, // TOIMPLEMENT
	ITEM_PICKUP, // TOIMPLEMENT
	ITEM_DROP, // TOIMPLEMENT
	ITEM_CRAFT, // TOIMPLEMENT
	ITEM_BREAK, // TOIMPLEMENT
	ITEM_EATEN, // TOIMPLEMENT
	CHEST_OPENED, // TOIMPLEMENT
	LINE_CHATTED, // TOIMPLEMENT
	COMMAND_EXECUTED, // TOIMPLEMENT
	ARROW_SHOT, // TOIMPLEMENT
	XP_COLLECTED, // TOIMPLEMENT
	DAMAGE_TAKEN, // TOIMPLEMENT
	ON_FIRE, // TOIMPLEMENT
	VOTE, // TOIMPLEMENT
	BUCKET_FILLED, // TOIMPLEMENT
	BUCKET_EMPTIED, // TOIMPLEMENT
	VILLAGER_TRADE, // TOIMPLEMENT
	TOKEN_EARNED, //TOIMPLEMENT
	CRANK_EXPLOEDED, //TOIMPLEMENT
}
