# Server Informations
server-name: unnamed
server-type: NOTHING
# Default alnguage for new users
default-lang: en_US
# Updater
update-type: MINOR
#SQL
sql-user:
sql-pass:
sql-port:
sql-db:
sql-host:
#WS
ws-user:
ws-pass:
#MapFolder
mapFolder:
#Licence
#If you don't have one, visit minidigger.me
licence: 
log-level: DEBUG
# Data - Do not change anything below this point!
spawn:
    default:
    premium:
    staff:
otherlocs:
    holos:
        1:
        2: