name: ${project.artifactId}
version: ${project.version}
author: MiniDigger
load: POSTWORLD
main: me.MiniDigger.Core.Core
description: The Core
website: minidigger.me
depend: [ProtocolLib,PermissionsEx]